Fix DB error updating category on PostgreSQL
ERROR: invalid input syntax for type integer: "TRUE" for the query:
UPDATE mantis_category_table SET name=$1, user_id=$2, status=$3
WHERE id=$4.

Regression introduced by commit 05c1639f45bfc0c3392288930f37f351bfcfc7b9
(issue #31017).

Fixes #36263