Fix error when updating category on PostgreSQL
Updating a category results in APPLICATION ERROR 401
Database query failed. Error received from database was #-1:
ERROR: invalid input syntax for type integer: "FALSE"

This is due to internally handling the category's status as a boolean,
while the underlying database column is an integer.

Typecasting the Checkbox post variable to int prevents the problem.

Fixes #35544