ADOdb pgsql fix: AlterColumnSQL incorrect SQL generated
Fixes behavior on PostgreSQL, where the schema.php upgrade step

$dict->AlterColumnSQL('mantis_user_pref_table', "redirect_delay I
NOTNULL DEFAULT 0" ) );

Generates incorrect SQL:

ALTER TABLE mantis_user_pref_table ALTER COLUMN INTEGER SET NOT NULL
ERROR: column "integer" of relation "mantis_user_pref_table" does not
exist

Porting part a) of commit 10871e5afc0bffc546b1a3d60bd7a459fa37e762

This issue exists in ADOdb <= 5.17. Upstream bug report
http://phplens.com/lens/lensforum/msgs.php?id=19202

Fixes #14398